#!/usr/bin/env bash

cp /autograder/submission/*.ml /autograder/source/bin/student.ml
cd /autograder/source

eval `opam config env --safe`

dune build bin/main.exe --profile release
if [ $? -eq 0 ]; then
    dune exec bin/main.exe --profile release
else
    cp ./error.json /autograder/results/results.json
fi
